### PR TITLE
Added support for OpenMP with AppleClang

### PR DESCRIPTION
**Pull request by ankane**
Hi, thanks for this library! This PR adds support for OpenMP with `AppleClang` as [outlined here](https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html). A few notes:

- cmake 3.0 is required to distinguish between `Clang` and `AppleClang` (and it must come before `project`)
- cmake 3.16 is required for `AppleClang` to properly find OpenMP without any configuration (relevant discussion for another project here: https://github.com/RGF-team/rgf/pull/316). This shouldn't be an issue for Apple users who typically use Homebrew which provides the latest cmake.
- It works both locally and on [GitHub Actions](https://github.com/ankane/ml-builds/runs/496495465?check_suite_focus=true)

Let me know what you think.

### CODE REVIEW

**Comment by masajiro** [comment]
Thank you for your PQ. It works well for GCC. However, how do you install openmp for clang? Is it only way to build it from source code?

**Comment by ankane** [comment]
The most common way I've seen is to install it with Homebrew.

```sh
brew install libomp
```

Here's an example: https://github.com/ankane/ml-builds/blob/ngt_openmp/.github/workflows/ngt-mac.yml

**Comment by masajiro** [comment]
Thanks! I should have looked at [the line](https://github.com/ankane/ml-builds/actions/runs/52584863/workflow#L12).

**Comment by ankane** [comment]
Thanks @masajiro. This should essentially solve #57 as well.

**Pull request merged**
